variables:
  vmImageName: "Ubuntu-latest"
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isRelease: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')]

stages:
  - stage: Test
    displayName: Test
    jobs:
      - job: Test
        pool:
          vmImage: $(vmImageName)
        variables:
          YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "10.x"
            displayName: "Install Node.js"
          - task: Cache@2
            inputs:
              key: 'yarn | "$(Agent.OS)" | yarn.lock'
              restoreKeys: |
                yarn | "$(Agent.OS)"
                yarn
              path: $(YARN_CACHE_FOLDER)
            displayName: Cache Yarn packages
          - script: |
              yarn --frozen-lockfile
            displayName: "Install"
          - script: |
              yarn lint
            displayName: "Lint"
          - script: |
              yarn test:unit
            displayName: "Test"
          - script: |
              yarn test:e2e:headless
            displayName: "E2E Test"
          - script: |
              yarn generate-thirdparty
            displayName: "Generate thirdparty"

  - stage: Build
    displayName: Build
    dependsOn: Test
    jobs:
      - job: Build
        pool:
          vmImage: $(vmImageName)
        variables:
          YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "10.x"
            displayName: "Install Node.js"
          - task: Cache@2
            inputs:
              key: 'yarn | "$(Agent.OS)" | yarn.lock'
              restoreKeys: |
                yarn | "$(Agent.OS)"
                yarn
              path: $(YARN_CACHE_FOLDER)
            displayName: Cache Yarn packages
          - script: |
              yarn --frozen-lockfile
            displayName: "Install"
          - script: |
              yarn build --mode production-test
            displayName: "Build"
          - publish: $(System.DefaultWorkingDirectory)/dist
            artifact: ElsaFrontendApp

  - stage: Deploy
    displayName: Deploy dev
    dependsOn: Build
    condition: and(succeeded(), eq(variables.isMain, true))
    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: "development"
        pool:
          vmImage: $(vmImageName)
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: ElsaFrontendApp
                - task: AWSCLI@1
                  inputs:
                    awsCredentials: "elsa-ci"
                    regionName: "eu-west-1"
                    awsCommand: "s3"
                    awsSubCommand: "rm"
                    awsArguments: "s3://kehitys.elsapalvelu.fi/  --recursive"
                - task: S3Upload@1
                  inputs:
                    awsCredentials: "elsa-ci"
                    regionName: "eu-west-1"
                    bucketName: "kehitys.elsapalvelu.fi"
                    sourceFolder: "$(Pipeline.Workspace)/ElsaFrontendApp"
                    globExpressions: "**"
                  displayName: "Deploy to S3"
                - task: AWSCLI@1
                  inputs:
                    awsCredentials: "elsa-ci"
                    regionName: "eu-west-1"
                    awsCommand: "cloudfront"
                    awsSubCommand: "create-invalidation"
                    awsArguments: '--distribution-id EXEO15DPST8ID --paths "/*"'

  - stage: DeployStaging
    displayName: Deploy staging
    dependsOn: Build
    condition: and(succeeded(), eq(variables.isRelease, true))
    jobs:
      - deployment: Deploy
        displayName: Deploy staging
        environment: "testi"
        pool:
          vmImage: $(vmImageName)
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: ElsaFrontendApp
                - task: AWSCLI@1
                  inputs:
                    awsCredentials: "staging-elsa-ci"
                    regionName: "eu-west-1"
                    awsCommand: "s3"
                    awsSubCommand: "rm"
                    awsArguments: "s3://testi.elsapalvelu.fi/  --recursive"
                - task: S3Upload@1
                  inputs:
                    awsCredentials: "staging-elsa-ci"
                    regionName: "eu-west-1"
                    bucketName: "testi.elsapalvelu.fi"
                    sourceFolder: "$(Pipeline.Workspace)/ElsaFrontendApp"
                    globExpressions: "**"
                  displayName: "Deploy to S3"
                - task: AWSCLI@1
                  inputs:
                    awsCredentials: "staging-elsa-ci"
                    regionName: "eu-west-1"
                    awsCommand: "cloudfront"
                    awsSubCommand: "create-invalidation"
                    awsArguments: '--distribution-id E45AQGQKD12C0 --paths "/*"'

  - stage: BuildProd
    displayName: Build prod
    dependsOn: Test
    condition: eq(variables.isRelease, true)
    jobs:
      - job: Build
        pool:
          vmImage: $(vmImageName)
        variables:
          YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "10.x"
            displayName: "Install Node.js"
          - task: Cache@2
            inputs:
              key: 'yarn | "$(Agent.OS)" | yarn.lock'
              restoreKeys: |
                yarn | "$(Agent.OS)"
                yarn
              path: $(YARN_CACHE_FOLDER)
            displayName: Cache Yarn packages
          - script: |
              yarn --frozen-lockfile
            displayName: "Install"
          - script: |
              yarn build
            displayName: "Build"
          - publish: $(System.DefaultWorkingDirectory)/dist
            artifact: ElsaFrontendAppProd

  - stage: DeployProd
    displayName: Deploy prod
    dependsOn:
      - BuildProd
      - DeployStaging
    condition: and(succeeded(), eq(variables.isRelease, true))
    jobs:
      - deployment: Deploy
        displayName: Deploy prod
        environment: "production"
        pool:
          vmImage: $(vmImageName)
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: ElsaFrontendAppProd
                - task: AWSCLI@1
                  inputs:
                    awsCredentials: "prod-elsa-ci"
                    regionName: "eu-west-1"
                    awsCommand: "s3"
                    awsSubCommand: "rm"
                    awsArguments: "s3://elsapalvelu.fi/  --recursive"
                - task: S3Upload@1
                  inputs:
                    awsCredentials: "prod-elsa-ci"
                    regionName: "eu-west-1"
                    bucketName: "elsapalvelu.fi"
                    sourceFolder: "$(Pipeline.Workspace)/ElsaFrontendAppProd"
                    globExpressions: "**"
                  displayName: "Deploy to S3"
                - task: AWSCLI@1
                  inputs:
                    awsCredentials: "prod-elsa-ci"
                    regionName: "eu-west-1"
                    awsCommand: "cloudfront"
                    awsSubCommand: "create-invalidation"
                    awsArguments: '--distribution-id E1FSXLBGWL4WJQ --paths "/*"'
